version: "3"

services:
  db1:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro

  db2:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro

  db3:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro

  db4:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db1
      - db2
      - db3
      - db4

  # db-loadbalancer:
  #   image: bitnami/pgbouncer:1.22
  #   environment:
  #     - POSTGRESQL_HOST=db1
  #     - POSTGRESQL_PASSWORD=postgres
  #     - POSTGRESQL_DATABASE=postgres
  #     - POSTGRESQL_USERNAME=postgres
  #     - PGBOUNCER_AUTH_TYPE=trust
  #     - PGBOUNCER_DSN_0=db1=host=pg1 port=5432 dbname=postgres
  #     - PGBOUNCER_DSN_1=db2=host=pg2 port=5432 dbname=postgres
  #     - PGBOUNCER_DSN_2=db3=host=pg3 port=5432 dbname=postgres
  #     - PGBOUNCER_DSN_3=db4=host=pg4 port=5432 dbname=postgres

  # app:
  #   build:
  #     context: ..
  #     dockerfile: backend/Dockerfile
